Hw 02
BolterBait/nodejs-rest-api pull request #1
Opened 2023-01-10 18:10 UTC by BolterBait

HW2 done. Please review it.

2023-01-10 19:18 UTC, KhYulian commented on app.js
> +  }
Мoжна скоротити використовуючи ||

2023-01-10 19:18 UTC, KhYulian commented on helpers/index.js
> +
використовуйте класи https://javascript.info/custom-errors

2023-01-10 19:19 UTC, KhYulian commented on models/contacts.js
> +  return (contacts);
дужки не потрібні в даному випадку

2023-01-10 19:19 UTC, KhYulian commented on routes/api/contacts.js
> +  })
Винесіть const schema  в окремий файл

2023-01-10 19:20 UTC, KhYulian commented on routes/api/contacts.js
> +  }
Здійснюйте валідацію в окремій middleware, яка спрацьовуватиме перед контроллером

2023-01-10 19:21 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-10 19:22 UTC, KhYulian commented
Відповідайте на коменти по мірі виправлення : )

2023-01-10 20:10 UTC, BolterBait commented on app.js
> +  }
app.use((err, req, res, next) => {
  if (err.status) {
    res.status(err.status || 500).json({ message: err.message || "Internal server error" })
  }
});

2023-01-10 20:20 UTC, KhYulian commented on app.js
> +  }
app.use((err, req, res, next) => {

  res.status(err.status || 500).json({ message: err.message || "Internal server error" })

});

2023-01-11 08:29 UTC, BolterBait commented on models/contacts.js
> +  return (contacts);
Прибрав

2023-01-11 08:41 UTC, BolterBait commented on helpers/index.js
> +
готово

2023-01-11 14:52 UTC, BolterBait commented on routes/api/contacts.js
> +  }
Готово

2023-01-11 14:53 UTC, BolterBait commented on routes/api/contacts.js
> +  })
Готово

2023-01-11 15:32 UTC, KhYulian approved these changes
Чудова робота :)

2023-01-11 15:32 UTC, merged